service: rust-ml-demo

provider:
  name: aws
  runtime: rust
  memoryize: 256

plugins:
  - serverless-rust

package:
  individually: true

functions:
  model:
    handler: rust-ml-demo
    events:
      - http:
          path: /model/{name}
          method: ANY
          request:
            parameters:
              paths:
                name: true
